DiaryWebApp/Models/ErrorViewModel.cs
namespace DiaryWebApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

DiaryWebApp/Controllers/HomeController.cs
using DiaryWebApp.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using ActionCoreLib;

namespace DiaryWebApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

DiaryWebApp/Controllers/ViewDiaryController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using ActionCoreLib.Models;
using ActionCoreLib.DbEntities;

namespace DiaryWebApp.Controllers
{
    public class ViewDiaryController : Controller
    {
        private readonly string dbName = ActionCoreLib.Utilities.GlobalConst.diaryPath;
        // GET: ViewDiaryController
        public ActionResult Index()
        {
           
            IEnumerable<DiaryModel> diaryList;
            using (var context = new DataContext(dbName))
            {
                diaryList = context.Diary.ToList();
            }
            return View(diaryList);
        }

        // GET: ViewDiaryController/Details/id
        public ActionResult Details(int id)
        {
            DiaryModel diaryModel;
            using (var context = new DataContext(dbName))
            {
                diaryModel = context.Diary.Find(id)!;
            }

            return View(diaryModel);
        }

        // GET: ViewDiaryController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ViewDiaryController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ViewDiaryController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: ViewDiaryController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ViewDiaryController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: ViewDiaryController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

DiaryWebApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

DiaryWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DiaryWebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DiaryWebApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DiaryWebApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ViewDiary" asp-action="Index">Diary</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - DiaryWebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

DiaryWebApp/Views/ViewDiary/Index.cshtml
@model IEnumerable<ActionCoreLib.Models.DiaryModel> 
@{
    ViewData["Title"] = "Privacy Policy";
    // Layout = "~/Views/Shared/_Layout.cshtml";
}
<head>
    <link rel="stylesheet" href="~/css/diaryview.css" />
  <style>
        .image-container {
            display: grid;
            grid-template-columns: repeat(4, 1fr);
            grid-gap: 10px;
        }

        .image-container img {
            width: 100%;
            height: auto;
            border-radius: 50%;
        }
  </style>
</head>
<div>
    <div class="image-container">
        @foreach (var item in @Model)
        {
            <img src="@item.ImageEntryTF" alt="Image" />
        }
    </div>
    <a href="add-data.html" id="add-button">
        +
    </a>
</div>